mapper:
  updateCondition:
    type: delay
    value: 1.0

  sensorMaxRange: 100

  mapperModule:
    - DynamicPointsMapperModule:
        thresholdDynamic: 0.75
        alpha: 0.8
        beta: 0.99
        beamHalfAngle: 0.017453292
        epsilonA: 0.01
        epsilonD: 0.01

    - PointDistanceMapperModule:
        minDistNewPoint: 0.3

input:
  - BoundingBoxDataPointsFilter:
      xMin: -0.5
      xMax: 1.5
      yMin: -1
      yMax: 1
      zMin: -1
      zMax: 0.5
      removeInside: 1

  - BoundingBoxDataPointsFilter:
      xMin: 1.5
      xMax: 6
      yMin: -2.5
      yMax: 2.5
      zMin: -1
      zMax: 1
      removeInside: 1

  - RandomSamplingDataPointsFilter:
      prob: 0.175

  - ObservationDirectionDataPointsFilter:

  - AddDescriptorDataPointsFilter:
      descriptorName: probabilityDynamic
      descriptorDimension: 1
      descriptorValues: [0.6] # This value is the initial probability of each point being dynamic

icp:
  outlierFilters:
    - TrimmedDistOutlierFilter:
        ratio: 0.75

  matcher:
    KDTreeMatcher:
      knn: 5
      epsilon: 1
      maxDist: 2.0

  errorMinimizer:
    PointToPointErrorMinimizer:
    # PointToPlaneErrorMinimizer:
    #   force4DOF: 1
    # IdentityErrorMinimizer:

  transformationCheckers:
    - CounterTransformationChecker:
        maxIterationCount: 40
    - DifferentialTransformationChecker:
        minDiffRotErr: 0.001
        minDiffTransErr: 0.01
        smoothLength: 3

  inspector: NullInspector

  logger: NullLogger

post:
  - CutAtDescriptorThresholdDataPointsFilter:
      descName: probabilityDynamic
      useLargerThan: 1
      threshold: 0.8

  - SurfaceNormalDataPointsFilter:
      knn: 10
